GET http://localhost:5211/book
###
GET http://localhost:5211/book/2
###
POST http://localhost:5211/book
Content-Type: application/json

{
    "title": "relife 3",
    "author": "idk now", 
    "publishyear": 2018
}

###
PUT http://localhost:5211/book/2
Content-Type: application/json

{
    "title": "hxh 2",
    "author": "idk", 
    "publishyear": 2011
}

###
DELETE http://localhost:5211/book/3