GET http://localhost:5211/book
###
GET http://localhost:5211/book/4
###
POST http://localhost:5211/book
Content-Type: application/json

{
    "title": "relife",
    "author": "idk now", 
    "publishyear": 2018
}

###
PUT http://localhost:5211/book/4
Content-Type: application/json

{
    "title": "hxh 2",
    "author": "idk", 
    "publishyear": 2011
}

###
DELETE http://localhost:5211/book/6